/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetV1BotsRequest {
    /**
     * Maximum number of bots to return (1-100)
     */
    limit?: number;
    /**
     * Number of bots to skip
     */
    offset?: number;
    /**
     * Filter by bot name (partial match)
     */
    name?: string;
    /**
     * Filter bots created after this date (ISO 8601 format)
     */
    created_after?: string;
    /**
     * Filter bots created before this date (ISO 8601 format)
     */
    created_before?: string;
}
