/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenmicApi from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "Updated Customer Support Bot",
 *         prompt: "You are an advanced customer support assistant with expertise in technical issues.",
 *         voice_speed: 1.1,
 *         llm_model_temperature: 0.8,
 *         call_settings: {
 *             max_call_duration: 15,
 *             silence_timeout: 20
 *         }
 *     }
 */
export interface UpdateBotRequest extends OpenmicApi.CreateBotRequest {}
