/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetV1PhoneNumbersRequest {
    /**
     * Maximum number of phone numbers to return (1-100)
     */
    limit?: number;
    /**
     * Number of phone numbers to skip
     */
    offset?: number;
    /**
     * Filter by phone number (partial match)
     */
    phone_number?: string;
    /**
     * Filter by name (partial match)
     */
    name?: string;
}
