/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         phone_number_id: "ybhb8wzi487w02m2bc7dh0ev",
 *         agent_id: "bvrg8wzi487w02m2bc7dh0ev",
 *         direction: "both"
 *     }
 */
export interface LinkBotToPhoneNumberRequest {
    /** Unique identifier of the phone number */
    phone_number_id: string;
    /** Bot UID to link */
    agent_id: string;
    /** Direction for the bot assignment */
    direction: LinkBotToPhoneNumberRequest.Direction;
}

export namespace LinkBotToPhoneNumberRequest {
    /**
     * Direction for the bot assignment
     */
    export type Direction = "inbound" | "outbound" | "both";
    export const Direction = {
        Inbound: "inbound",
        Outbound: "outbound",
        Both: "both",
    } as const;
}
