/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         phone_number_id: "ybhb8wzi487w02m2bc7dh0ev",
 *         direction: "inbound"
 *     }
 */
export interface PostV1PhoneNumbersUnlinkAgentRequest {
    /** The unique identifier of the phone number */
    phone_number_id: string;
    /** Direction to unlink (inbound, outbound, or both) */
    direction: PostV1PhoneNumbersUnlinkAgentRequest.Direction;
}

export namespace PostV1PhoneNumbersUnlinkAgentRequest {
    /**
     * Direction to unlink (inbound, outbound, or both)
     */
    export type Direction = "inbound" | "outbound" | "both";
    export const Direction = {
        Inbound: "inbound",
        Outbound: "outbound",
        Both: "both",
    } as const;
}
