/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AdvancedSettings {
    /** Personality type for the agent */
    agent_personality?: AdvancedSettings.AgentPersonality;
    /** Whether to humanize the conversation */
    humanize_conversation?: boolean;
    /** Whether to reduce background noise */
    background_noise_reduction?: boolean;
    /** Whether to allow user interruptions */
    allow_interruptions?: boolean;
    /** Minimum interruption duration in seconds (0.2-5, step 0.1) */
    min_interruption_duration?: number;
    /** Background sound to play */
    background_sound?: string;
    /** Preferred response length */
    agent_response_length?: AdvancedSettings.AgentResponseLength;
    /** Short pause duration in seconds (0.2-2, step 0.1) */
    short_pause?: number;
    /** Long pause duration in seconds (0.5-6, step 0.1) */
    long_pause?: number;
    /** Phrases to filter from speech */
    filter_phrases?: string;
}

export namespace AdvancedSettings {
    /**
     * Personality type for the agent
     */
    export type AgentPersonality = "casual" | "humorous" | "direct" | "formal" | "persuasive" | "friendly";
    export const AgentPersonality = {
        Casual: "casual",
        Humorous: "humorous",
        Direct: "direct",
        Formal: "formal",
        Persuasive: "persuasive",
        Friendly: "friendly",
    } as const;
    /**
     * Preferred response length
     */
    export type AgentResponseLength = "normal" | "short" | "concise" | "long";
    export const AgentResponseLength = {
        Normal: "normal",
        Short: "short",
        Concise: "concise",
        Long: "long",
    } as const;
}
