/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenmicApi from "../index.js";

export interface BotResponse {
    /** Unique identifier of the bot */
    uid: string;
    /** Name of the bot */
    name: string;
    /** System prompt for the bot */
    prompt: string;
    /** Initial message the bot will send */
    first_message?: string;
    /** ID of the knowledge base */
    knowledge_base_id?: number;
    /** Voice synthesis provider */
    voice_provider?: BotResponse.VoiceProvider;
    /** Voice ID or name */
    voice?: string;
    /** Voice model being used */
    voice_model?: string;
    /** Speech speed multiplier */
    voice_speed?: number;
    /** Large language model being used */
    llm_model_name?: string;
    /** Temperature setting for the LLM */
    llm_model_temperature?: number;
    /** Speech-to-text provider */
    stt_provider?: "Deepgram";
    /** Speech-to-text model */
    stt_model?: string;
    call_settings?: OpenmicApi.CallSettings;
    advanced_settings?: OpenmicApi.AdvancedSettings;
    post_call_settings?: OpenmicApi.PostCallSettings;
    /** Bot creation timestamp */
    created_at: string;
    /** Bot last update timestamp */
    updated_at: string;
}

export namespace BotResponse {
    /**
     * Voice synthesis provider
     */
    export type VoiceProvider = "OpenAI" | "ElevenLabs" | "Deepgram";
    export const VoiceProvider = {
        OpenAi: "OpenAI",
        ElevenLabs: "ElevenLabs",
        Deepgram: "Deepgram",
    } as const;
}
