/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CallSettings {
    /** Maximum call duration in minutes (2-30) */
    max_call_duration?: number;
    /** Silence timeout in seconds (5-45) */
    silence_timeout?: number;
    /** Maximum retries for silence timeout (1-5) */
    silence_timeout_max_retries?: number;
    /** Message to play when silence timeout occurs */
    silence_timeout_message?: string;
    /** Whether to record calls */
    call_recording_enabled?: boolean;
    /** Whether to detect voicemail */
    voicemail_detection_enabled?: boolean;
    /** Whether HIPAA compliance is enabled */
    hipaa_compliance_enabled?: boolean;
    /** Whether PCI compliance is enabled */
    pci_compliance_enabled?: boolean;
}
