/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenmicApi from "../index.js";

export interface CreateBotRequest {
    /** Name of the bot (max 255 characters) */
    name: string;
    /** System prompt for the bot */
    prompt: string;
    /** Initial message the bot will send */
    first_message?: string;
    /** ID of the knowledge base to use */
    knowledge_base_id?: number;
    /** Voice synthesis provider */
    voice_provider?: CreateBotRequest.VoiceProvider;
    /** Voice ID or name */
    voice?: string;
    /** Voice model to use */
    voice_model?: string;
    /** Speech speed multiplier */
    voice_speed?: number;
    /** Large language model to use */
    llm_model_name?: string;
    /** Temperature setting for the LLM */
    llm_model_temperature?: number;
    /** Speech-to-text provider */
    stt_provider?: "Deepgram";
    /** Speech-to-text model */
    stt_model?: string;
    call_settings?: OpenmicApi.CallSettings;
    advanced_settings?: OpenmicApi.AdvancedSettings;
    post_call_settings?: OpenmicApi.PostCallSettings;
}

export namespace CreateBotRequest {
    /**
     * Voice synthesis provider
     */
    export type VoiceProvider = "OpenAI" | "ElevenLabs" | "Deepgram";
    export const VoiceProvider = {
        OpenAi: "OpenAI",
        ElevenLabs: "ElevenLabs",
        Deepgram: "Deepgram",
    } as const;
}
