/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Error_ {
    /** Error message */
    error: string;
    /** Additional error message (for certain error types) */
    message?: string;
}
