/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenmicApi from "../index.js";

export interface ListPhoneNumbersResponse {
    phone_numbers: OpenmicApi.PhoneNumberResponse[];
    pagination: OpenmicApi.Pagination;
}
