/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenmicApi from "../index.js";

export interface ListCallsResponse {
    calls: OpenmicApi.CallResponse[];
    pagination: OpenmicApi.Pagination;
}
