/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PhoneNumberResponse {
    /** Unique identifier of the phone number */
    phone_number_id: string;
    /** Phone number in E.164 format */
    phone_number: string;
    /** Friendly name for the phone number */
    name?: string;
    /** Bot UID for inbound calls */
    inbound_agent_id?: string;
    /** Bot UID for outbound calls */
    outbound_agent_id?: string;
    /** Phone number creation timestamp */
    created_at: string;
    /** Phone number last update timestamp */
    updated_at: string;
}
