/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PostCallSettings {
    /** Prompt for generating call summary */
    summary_prompt?: string;
    /** Prompt for evaluating call success */
    success_evaluation_prompt?: string;
    /** Type of success evaluation rubric */
    success_evaluation_rubric_type?: PostCallSettings.SuccessEvaluationRubricType;
    /** Prompt for structured data extraction */
    structured_extraction_prompt?: string;
    /** JSON schema for structured extraction */
    structured_extraction_json_schema?: Record<string, unknown>;
}

export namespace PostCallSettings {
    /**
     * Type of success evaluation rubric
     */
    export type SuccessEvaluationRubricType =
        | "NUMERIC_SCALE"
        | "DESCRIPTIVE_SCALE"
        | "PERCENTAGE_SCALE"
        | "LIKERT_SCALE"
        | "PASS_FAIL"
        | "SENTIMENT";
    export const SuccessEvaluationRubricType = {
        NumericScale: "NUMERIC_SCALE",
        DescriptiveScale: "DESCRIPTIVE_SCALE",
        PercentageScale: "PERCENTAGE_SCALE",
        LikertScale: "LIKERT_SCALE",
        PassFail: "PASS_FAIL",
        Sentiment: "SENTIMENT",
    } as const;
}
