/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class OpenmicApiTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, OpenmicApiTimeoutError.prototype);
    }
}
