/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Bots } from "./api/resources/bots/client/Client.js";
import { Calls } from "./api/resources/calls/client/Client.js";
import { PhoneNumbers } from "./api/resources/phoneNumbers/client/Client.js";

export declare namespace OpenmicApiClient {
    export interface Options {
        environment?: core.Supplier<environments.OpenmicApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class OpenmicApiClient {
    protected readonly _options: OpenmicApiClient.Options;
    protected _bots: Bots | undefined;
    protected _calls: Calls | undefined;
    protected _phoneNumbers: PhoneNumbers | undefined;

    constructor(_options: OpenmicApiClient.Options) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get bots(): Bots {
        return (this._bots ??= new Bots(this._options));
    }

    public get calls(): Calls {
        return (this._calls ??= new Calls(this._options));
    }

    public get phoneNumbers(): PhoneNumbers {
        return (this._phoneNumbers ??= new PhoneNumbers(this._options));
    }
}
