/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const OpenmicApiEnvironment = {
    Default: "https://api.openmic.ai",
} as const;

export type OpenmicApiEnvironment = typeof OpenmicApiEnvironment.Default;
