/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         from_number: "+1234567890",
 *         to_number: "+0987654321",
 *         override_agent_id: "bvrg8wzi487w02m2bc7dh0ev",
 *         customer_id: "customer_001",
 *         dynamic_variables: {
 *             "name": "John"
 *         },
 *         callback_url: "https://example.com/callback"
 *     }
 */
export interface CreateCallRequest {
    /** The number you own in E.164 format. Must be a number purchased from OpenMic. */
    from_number: string;
    /** The number you want to call in E.164 format. */
    to_number: string;
    /** The bot UID to override the default agent. */
    override_agent_id?: string;
    /** Customer identifier for tracking */
    customer_id?: string;
    /** Send dynamic variables in key value pairs to replace in the prompt. */
    dynamic_variables?: Record<string, unknown>;
    /** Callback URL to receive call events. */
    callback_url?: string;
}
