/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpenmicApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetV1CallsRequest {
    /**
     * Maximum number of calls to return (1-100)
     */
    limit?: number;
    /**
     * Number of calls to skip
     */
    offset?: number;
    /**
     * Filter by customer ID
     */
    customer_id?: string;
    /**
     * Filter by originating phone number
     */
    from_number?: string;
    /**
     * Filter by destination phone number
     */
    to_number?: string;
    /**
     * Filter by bot ID
     */
    bot_id?: string;
    /**
     * Filter calls from this date (ISO 8601 format)
     */
    from_date?: string;
    /**
     * Filter calls to this date (ISO 8601 format)
     */
    to_date?: string;
    /**
     * Filter by call status
     */
    call_status?: OpenmicApi.GetV1CallsRequestCallStatus;
    /**
     * Filter by call type
     */
    call_type?: OpenmicApi.GetV1CallsRequestCallType;
}
