/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetV1CallsRequestCallStatus = "registered" | "ongoing" | "ended" | "error";
export const GetV1CallsRequestCallStatus = {
    Registered: "registered",
    Ongoing: "ongoing",
    Ended: "ended",
    Error: "error",
} as const;
