/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetV1CallsRequestCallType = "phonecall" | "webcall";
export const GetV1CallsRequestCallType = {
    Phonecall: "phonecall",
    Webcall: "webcall",
} as const;
