# This file was auto-generated by Fern from our API Definition.

import typing

AdvancedSettingsAgentPersonality = typing.Union[
    typing.Literal["casual", "humorous", "direct", "formal", "persuasive", "friendly"], typing.Any
]
