# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .advanced_settings import AdvancedSettings
from .call_settings import CallSettings
from .create_bot_request_voice_provider import CreateBotRequestVoiceProvider
from .post_call_settings import PostCallSettings


class CreateBotRequest(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Name of the bot (max 255 characters)
    """

    prompt: str = pydantic.Field()
    """
    System prompt for the bot
    """

    first_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Initial message the bot will send
    """

    knowledge_base_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    ID of the knowledge base to use
    """

    voice_provider: typing.Optional[CreateBotRequestVoiceProvider] = pydantic.Field(default=None)
    """
    Voice synthesis provider
    """

    voice: typing.Optional[str] = pydantic.Field(default=None)
    """
    Voice ID or name
    """

    voice_model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Voice model to use
    """

    voice_speed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speech speed multiplier
    """

    llm_model_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Large language model to use
    """

    llm_model_temperature: typing.Optional[float] = pydantic.Field(default=None)
    """
    Temperature setting for the LLM
    """

    stt_provider: typing.Optional[typing.Literal["Deepgram"]] = pydantic.Field(default=None)
    """
    Speech-to-text provider
    """

    stt_model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Speech-to-text model
    """

    call_settings: typing.Optional[CallSettings] = None
    advanced_settings: typing.Optional[AdvancedSettings] = None
    post_call_settings: typing.Optional[PostCallSettings] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
