# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class LinkBotToPhoneNumberResponse(UniversalBaseModel):
    phone_number_id: str = pydantic.Field()
    """
    Unique identifier of the phone number
    """

    phone_number: str = pydantic.Field()
    """
    Phone number in E.164 format
    """

    inbound_agent_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Bot UID for inbound calls
    """

    outbound_agent_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Bot UID for outbound calls
    """

    message: str = pydantic.Field()
    """
    Success message
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
