# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Pagination(UniversalBaseModel):
    limit: int = pydantic.Field()
    """
    Number of items per page
    """

    offset: int = pydantic.Field()
    """
    Number of items skipped
    """

    total: int = pydantic.Field()
    """
    Total number of items
    """

    has_more: bool = pydantic.Field()
    """
    Whether there are more items
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
